### ISSUE TITLE
Server problem with ots_create_tidy_data

### ISSUE THREAD

**Issue by nvilloria** [ropensci/tradestatistics#12]
there seems to be a server side glitch. For example,

ots_create_tidy_data(years = 1975, reporters = "chl", partners = "arg", table = "yrp", max_attempts = 35)

produces the following error message:

Error in ots_read_from_api(year, reporter, partner, product_code_length,  : 
  
        It wasn't possible to obtain data.
        Provided this function tests your internet connection 
        you misspelled a reporter, partner or table, or there was 
        a server problem.
        Please check and try again.

(I tried with other tables, with the same result.) Any suggestion as to how solve this?

**Comment by pachamaltese** [comment]
@nvilloria sorry for the late reply, there was a problem with the physical server, after rebooting it remotely it worked

I checked both via package and via brower, this is:
```
package: ots_create_tidy_data(years = 1975, reporters = "chl", partners = "arg", table = "yrp", max_attempts = 1)
browser: https://api.tradestatistics.io/yrp?r=chl&p=arg&y=1975
```
