### ISSUE TITLE
The ots_create_tidy_data() function does not work.

### ISSUE THREAD

**Issue by gueyenono** [ropensci/tradestatistics#21]
I just installed the `tradestatistics` package on a new machine and, oddly enough, the `ots_create_tidy_data()` does not work. I tried getting data using the example in the help file, but I get the following error message:

```
ots_create_tidy_data(years = 1980, reporters = "chl", products = "0101", table = "yrc")
Error: lexical error: invalid char in json text.
                                       <html>  <head><title>502 Bad Ga
                     (right here) ------^
```

I even tried it with the development version, but the error persists.

**Comment by pachamaltese** [comment]
Hi

Sorry. The server had a problem. Technical service shall fix the issue soon
if I don't get it first. I'll let u know.

**Comment by pachamaltese** [comment]
@gueyenono Hi!!

please do this from R

```
library(devtools)
install_github("ropensci/tradestatistics")
```

I optimized the package a bit, there are some API changes after the service interruption bc of problems with the server

I just sent the new version of the package to CRAN

**Comment by gueyenono** [comment]
Thank you very much.

**Comment by pachamaltese** [comment]
@gueyenono Hi! I had to turn off the server and move to a new server, sorry about that.
To compensate the service interruptions (I bet 100 dollars that you downloaded incomplete datasets) I can prepare a google drive folder or whatever you like with the data you require. My fault, my repair. I apologize for any problem you might had from this.
My email is m vargas at dcc uchile cl. Just tell me "I need XXX data for YYY country/region" and I'll prepare it.

**Comment by gueyenono** [comment]
@pachamaltese Thank you very much for your hard work. I actually do not need the data immediately. I just wanted to stay on top of things to prep the code for a international trade course I am currently teaching. The data will be needed in about 2 weeks or so. If things change I will be sure to let you know.

**Comment by pachamaltese** [comment]
glad to know that, but provided I have users tonight I'm not sleeping much
do not hesitate to contact me, I'll let u know asap when I migrate all the contents

**Comment by pachamaltese** [comment]
Hi @gueyeyono
The API is finally working. I had to create the db and files again in a
migrated machine.
Please run install.packages("tradestatistics") and use v0.2.4. There are
some API changes that don't work well with older versions.

**Comment by gueyenono** [comment]
@pachamaltese It is working perfectly. Once again, thank you very much for your hard work.

**Comment by pachamaltese** [comment]
@gueyenono Hi! Just a follow up, v0.2.5 is on CRAN, it shall easy data
extraction a bit, for example you can do this with API changes:
Ots_create_tidy_data(... Reporters = c("fra", "ita", *rest of the EU*) ...)
And it will return a single data frame with more than 1 reporter. It is
explained here:
https://ropensci.github.io/tradestatistics/
Once again, sorry 4 the server problem, at least I used the downtime to
improve things up
Best!
