### ISSUE TITLE
Add easy cache

### ISSUE THREAD

**Issue by eliocamp** [ropensci/tradestatistics#29]
On [your workshop](https://github.com/pachamaltese/r-users-groups/blob/master/buenos-aires/2019-12-14/01-dplyr/01-dplyr.Rmd) you use manual caching of results with code like this

```r
yr_rda <- "yr.rda"
if (!file.exists(yr_rda)) {
  yr <- ots_create_tidy_data(years = 2000:2018, reporters = "arg", table = "yr")
  save(yr, file =  yr_rda, compress = "xz")
} else {
  load(yr_rda)
}
yr
```

How about adding cache logic inside {tradestatistics}, This would make it easier for user to cache data and lighten the load on your servers. I implemented an example of cache logic that works both in memory (using {memoise}) and on disk [here](https://github.com/boshek/rsoi/issues/18#issuecomment-546963106).

**Comment by pachamaltese** [comment]
Dear @eliocamp 
Please feel free to edit the code as you want but please send me a PR.
Thanks a lot!!!!

**Comment by pachamaltese** [comment]
@eliocamp once again, thanks a lot for this suggestion
I just discussed this with @jbkunst and he proposes that using memoise to save API caches in the server would be another cool improvement

**Comment by eliocamp** [comment]
Sounds cool. I'm not sure where those computations are performed (e.g. which repo). 

Regarding this change, am I correct in that the only functions which make API requests are `ots_create_tidy_data()` and `ots_read_from_api()`. Those are the only ones that need cache?

**Comment by pachamaltese** [comment]
Dear @eliocamp 
I merged and closed #30. I did implemented some changes for consistent notation with the rest of the functions and I applied styler.
So far, the only functionality I cannot get to work is in-memory caching, but caching on disk is working well.

**Comment by vsoch** [comment]
Should this be closed?

**Comment by pachamaltese** [comment]
Let me check if I fixed in-memory caching

**Comment by pachamaltese** [comment]
closed, sent to CRAN with an edited version of these changes (v0.2.7) https://cran.r-project.org/web/packages/tradestatistics/index.html
