### ISSUE TITLE
1980s data and Export/Import 

### ISSUE THREAD

**Issue by tdouthat** [ropensci/tradestatistics#36]
Dr. Vargas and Team, 

Firstly, let me tip my hat to your amazing work. I have some question about the 1980s product data. As I can understand, it is from the Feenstra et al. data set, but I don't see SITC4 codes, and when I querry 1989, which I assume is from this dataset, but I don't think your tables have the STIC4 codes, and when I try to query used tires (tyres) and retreads, I get zero results, but when I query rubber products I get an array of product flows from the 1980s, but not 4012. 

yrpc1 <- ots_create_tidy_data(years = 1989, reporters = "all", partners = c("aia","atg","arb","bhs","brb","vgb","cym","cck","cub","dma","dom","glp","hti","jam","mtq","msr","ant","lca", "vct"), products = "4012", table = "yrpc")

I am also reading your documentation from here (https://docs.tradestatistics.io/data-processing.html#filling-gaps-in-our-data) in section 2.2 Filling gaps in our data, and was wondering if the tidy_data imports were already corrected, or if there were code. I looked through the manual but cold not find this (very possibly my own oversight or misunderstanding). 

I was also wondering how you treated the stable unit problem in cases, e.g., Netherlands Antilles, where there have been admin changes in the ISO or 3 digit country codes. 

Many thanks in advance.

**Comment by pachadotdev** [comment]
hi
so sorry for the slow reply, this data does not come from Feenstra (that's another dataset)
here I used an armonization method to symmetrize flows, an all the data is in HS07 (Feenstra uses SITC)
all the flow are corrected in the server
I doubt that my answer is still useful, but please @  me if you have more questions
You can see the treatment of some varying ISO codes here https://github.com/tradestatistics/yearly-datasets/blob/master/0-2-clean-data.R#L67
