### ISSUE TITLE
ots_inflation_adjustment() drops reference year

### ISSUE THREAD

**Issue by michalovadek** [ropensci/tradestatistics#38]
Hi, thanks for this super useful package. I noticed running ots_inflation_adjustment() shrank the original dataset and then realized this was due to the reference year being dropped. If this is desired behaviour, it would be good to add it to the function documentation. I would argue though that if the data for the reference year are found in the original data.frame, it should simply be left there unchanged.

**Comment by pachadotdev** [comment]
hi Michael
so sorry for the delay (writing thesis here, but still inexcusable)
please @ me when you have questions
and yes, for my uses I drop the reference year since the factor for it is 1
I'll change that for the next version

**Comment by pachadotdev** [comment]
hi @michalovadek 
sorry for the delays, i just repaired my laptop, and now i'm updating the API and the functions to keep the reference year

**Comment by pachadotdev** [comment]
@michalovadek Hi!! I have updated the function, but more important than it: I've tested the update and it works properly
I've also changes the input data for the discount rate, and now I'm using the weighted median, as I noticed that some years with hiper-inflation in some countries really distorted the mean
