### ISSUE TITLE
Package back to CRAN?

### ISSUE THREAD

**Issue by SebKrantz** [ropensci/tradestatistics#44]
Hello, I think this is a great project and wanted to inquire about it's status. The R package was removed in April this year. Are the packages and data still maintained / updated?

**Comment by pachadotdev** [comment]
hi!
it is, I'm actually working on data updates that shall be publicly available after christmas
the CRAN removal was because of a test that used the API, I can remove that single test and submit again, but the priority now is my own work, so I'll come with a large update around Dec 25-30

**Comment by pachadotdev** [comment]
@SebKrantz hi, the new API is online (i.e. see https://api.tradestatistics.io/__docs__/). It included newer tables with imputation and the old tables as is are still there. The package on GitHub was updated as well, and also the dashboard (shiny.tradestatistics.io)!

**Comment by SebKrantz** [comment]
Great, thanks a lot! I will check it out as I find time. Cheers.
