### ISSUE TITLE
Error in parse_con

### ISSUE THREAD

**Issue by nlsolutions** [ropensci/tradestatistics#59]
Hello, I'm getting the below error in RStudio when trying to run a simple example:

`ots_create_tidy_data(years = 2002, reporters = "chl", partners = "chn")`

Error:

`Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                       year 2002 2020 
                     (right here) ------^`

Any idea how to resolve this?

**Comment by dakilian** [comment]
Me too!

**Comment by nestorgr** [comment]
It is my case too

**Comment by pachadotdev** [comment]
hi @nlsolutions, @dakilian @nestorgr 
it's working fine here, but please confirm that you installed the newest version of the package (i.e. `remotes::install_github("ropensci/tradestatistics")` 
I had to re-deploy everything bc a students broke the server

**Comment by istrazivac** [comment]
Hi, I had the same issue as @nlsolutions, @dakilian @nestorgr (pars_con) and after installing the newest version of the package via remotes, it works like a charm. Thank you @pachadotdev.

**Comment by pachadotdev** [comment]
> Hi, I had the same issue as @nlsolutions, @dakilian @nestorgr (pars_con) and after installing the newest version of the package via remotes, it works like a charm. Thank you @pachadotdev.

thanks for your confirmation!!
I had to redeploy, please report back if you see anything strange when plotting etc
I took extra care when creating the SQL database, but re deployments are always complicated
