### ISSUE TITLE
tradestatistics::ots_create_tidy_data not working

### ISSUE THREAD

**Issue by daoudaamad** [ropensci/tradestatistics#60]
I am working with the tradestatistics package to download international trade data. But I still get the same message when running this command:

ots_create_tidy_data(
  years = 2019,
  reporters = "all",
  partners = "all",
  commodities = "all",
  table = "yr",
  max_attempts = 5,
  use_cache = FALSE,
  file = NULL,
  use_localhost = FALSE
)

Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                       year 2002 2020 
                     (right here) ------^

I really don't understand the origin of the problem..

**Comment by pachadotdev** [comment]
hi @daoudaamad 
please reinstall the pkg with `remotes::install_github("ropensci/tradestatistics")` 
i had to re-deploy in recent weeks, and also the `use_localhost` argument is not in use anymore
