### ISSUE TITLE
ots_create_tidy_data not working

### ISSUE THREAD

**Issue by sebar84** [ropensci/tradestatistics#67]
Hello. I  get the next message when running this command:

yr <- ots_create_tidy_data(
  years = 2019,
  table = "yr"
)

Message:

Error in file(file, "rt") : 
  cannot open the connection to 'https://api.tradestatistics.io/year_range'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://api.tradestatistics.io/year_range': HTTP status was '502 Bad Gateway'
Error in year_range$year : $ operator is invalid for atomic vectors
Error in min(year_range):max(year_range) : NA/NaN argument
In addition: Warning messages:
1: In years %in% min(year_range):max(year_range) :
  NAs introduced by coercion
2: In years %in% min(year_range):max(year_range) :
  NAs introduced by coercion

Thanks

**Comment by pachadotdev** [comment]
hi @sebar84 
thanks! I rebooted the server and now it works
