### ISSUE TITLE
Server down - temporary? 

### ISSUE THREAD

**Issue by shartmann1102** [ropensci/tradestatistics#69]
Hi guys, 

first of all many thanks for the package - fantastic work. 

I just realised, however, the server api.tradestatistics.io seems to be down, is this a temporary thing? 

Many thanks! 

Best, 
Sven 

Issue in R: 

> trade_data_bilateral <- ots_create_tidy_data(
+   reporters = "all",
+   partners = "all",
+   years = 2002:2020,
+   table = "yrp"
+ )
Error in file(file, "rt") : 
  cannot open the connection to 'https://api.tradestatistics.io/year_range'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://api.tradestatistics.io/year_range': HTTP status was '502 Bad Gateway'
Error in year_range$year : $ operator is invalid for atomic vectors
Error in min(year_range):max(year_range) : NA/NaN argument
In addition: Warning messages:
1: In years %in% min(year_range):max(year_range) :
  NAs introduced by coercion
2: In years %in% min(year_range):max(year_range) :
  NAs introduced by coercion

**Comment by ga-it** [comment]
Same issue

Web shiny app is working but not API

**Comment by pachadotdev** [comment]
@ga-it @shartmann1102 fixed!
sometimes there are many users connected and the OS kills the process
