### ISSUE TITLE
Invalid: Parquet magic bytes not found in footer ... It wasn't possible to obtain data.

### ISSUE THREAD

**Issue by andreaspacher** [ropensci/tradestatistics#74]
Hello, thanks for the useful work with tradestatistics!

The following code used to work well:

```
jpn.ots <- ots_create_tidy_data(
  years = min_year:2020, # I would do "min_year:max_year", but unfortunately there are only data until 2020
  reporters = "jpn",
  #partners = "arg",
  table = "yrp" 
)
```

... however, now I get the error:

Downloading data for the combination 2008, jpn, all...
Error : Invalid: Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.
Error in ots_read_from_api(table = table, max_attempts = max_attempts,  : 
  It wasn't possible to obtain data. Provided this function tests your internet connection
you misspelled a reporter, partner or table, or there was a server problem. Please check and try again.

**Comment by pachadotdev** [comment]
hi @andreaspacher 
are you using the most recent version of the package?

**Comment by pachadotdev** [comment]
let me know, I just installed the github version and it works (same as the cran version)

i can provide you a sql dump if that works better for you

**Comment by andreaspacher** [comment]
Hello @pachadotdev, thanks for your quick response -- you were right, after having installed the most recent version, it worked again! Thanks a lot!

**Comment by pachadotdev** [comment]
> Hello @pachadotdev, thanks for your quick response -- you were right, after having installed the most recent version, it worked again! Thanks a lot!

the package (and the api) have changed considerably since 2017, i hope to have a final version by next year

**Comment by pachadotdev** [comment]
@andreaspacher hi! I just uploaded a new database version that dates back to 1980, the new pkg should be on CRAN in the next days. In the meanwhile, the package works but will not lett you download anything before 2002 even with the new database.
