### ISSUE TITLE
use a news file, git tags, and release notes

### ISSUE THREAD

**Issue by sckott** [ropensci/tradestatistics#9]
hi 👋  

We want all rOpenSci pkgs to consistently keep track of changes. please do the below from now on:

- use a NEWS.md file, do not add this file to .Rbuildignore, as you want the file to be on the CRAN page for your pkg, a good example to follow: https://github.com/ropensci/drake/blob/master/NEWS.md
- git tag each CRAN version, to git tag commits for previous CRAN versions, you can find the commit, then do e.g., `git tag -a v1.2 9fceb02` where `9fceb02` is the commit sha
- use the [releases tab](https://github.com/ropensci/tradestatistics/releases) in this repo to include the associated NEWS items for each tag/version, e.g., see https://github.com/ropensci/taxize/releases/tag/v0.8.8

**Comment by pachamaltese** [comment]
closed in PR #15
